stages:
  - cmake
  - build
  - post

# Unix Build
cmake:
  stage: cmake
  image: luki42/dynuiprefresher_build:latest
  script:
    - cmake -S . -B build
  artifacts:
    paths:
      - build/
      - inc/
      - postinst

build:
  stage: build
  image: luki42/dynuiprefresher_build:latest
  script:
    - cd build
    - make iprefresher
  artifacts:
    paths:
      - build/
      - inc/
      - postinst
  dependencies:
    - cmake


build_package:
  stage: post
  image: luki42/dynuiprefresher_build:latest
  script:
    - cd build
    - make package
  artifacts:
    paths:
      - build/
      - inc/
      - postinst
  dependencies:
    - build

test:
  stage: post
  image: luki42/dynuiprefresher_build:latest
  script:
    - cd build
    - make test
    - make build-xml
  artifacts:
    reports:
      junit: build/report.xml
    paths:
      - build/
      - inc/
      - postinst
  dependencies:
    - build

# Windows Build
cmake_win64:
  stage: cmake
  image: luki42/dynuiprefresher_build:windows
  script:
    - cmake -S . -B build -D WinBuild=ON
  artifacts:
    paths:
      - build/
      - inc/

build_win64:
  stage: build
  image: luki42/dynuiprefresher_build:windows
  script:
    - cd build
    - make iprefresher
  artifacts:
    paths:
      - build/
      - inc/
  dependencies:
    - cmake_win64


build_package_win64:
  stage: post
  image: luki42/dynuiprefresher_build:windows
  script:
    - cd build
    - make package
  artifacts:
    paths:
      - build/
      - inc/
  dependencies:
    - build_win64