image: luki42/dynuiprefresher_build:latest

stages:
  - build


build:
  stage: build
  script:
    - cmake -S . -B build
    - cd build
    - make
    - make package
    - make test
    - make build-xml
  artifacts:
    paths:
      - "build/bin/*"
      - "build/packages/*"
    reports:
      junit: report.xml