image: luki42/dynuiprefresher_build:latest

stages:
  - cmake
  - build
  - build_package
  - test

cmake:
  stage: cmake
  script:
    - cmake -S . -B build
  cache:
    paths:
      - ./

build:
  stage: build
  script:
    - cd build
    - make
  cache:
    paths:
      - ./
  artifacts:
    paths:
      - "build/bin/*"


build_package:
  stage: build_package
  script:
    - cd build
    - make package
  cache:
    paths:
      - ./
  artifacts:
    paths:
      - "build/packages/*"

test:
  stage: test
  script:
    - cd build
    - make test
    - make build-xml
  artifacts:
    reports:
      junit: build/report.xml