image: luki42/dynuiprefresher_build:latest

stages:
  - cmake
  - build
  - build_package
  - test

cache:
  paths:
    - build/
    - src/
    - inc/
    - tests/
    - postinst

cmake:
  stage: cmake
  script:
    - cmake -S . -B build

build:
  stage: build
  script:
    - cd build
    - make
  artifacts:
    paths:
      - "build/bin/*"


build_package:
  stage: build_package
  script:
    - cd build
    - make package
  artifacts:
    paths:
      - "build/packages/*"

test:
  stage: test
  script:
    - cd build
    - make test
    - make build-xml
  artifacts:
    reports:
      junit: build/report.xml